# Configure Hugo site
# https://gohugo.io/getting-started/configuration/

baseURL = "https://momoto.github.io/"
languageCode = "en-us"
title = "Seiji Momoto"
googleAnalytics = "UA-29340465-5"

archetypeDir = "archetypes" # The directory where Hugo finds archetype files.
dataDir = "data"            # The directory from where Hugo reads data files.
resourceDir = "resources"   # where the files cache will be stored. 
contentDir = "content"      # The directory from where Hugo reads content files.
layoutDir = "layouts"       # The directory from where Hugo reads layouts (templates).
staticDir = "static"        # A directory or a list of directories from where Hugo reads static files.
publishDir = "public"       # The directory to where Hugo will write the final static site.

disableKinds = [
    # "page", "home", "section", "sitemap", "robotsTXT", "404"
    "taxonomy", "taxonomyTerm", "RSS"
]

[params]
    theme_color = "#574CDD"
    description = "works on business applications and Dynamics 365 Business Central"
    description_photo = "avatar.jpg"
    favicon = "identicon.png"
    logo = "identicon.png"

[params.hero]
    avatar = "avatar.jpg"
    subtitle = "Seiji Momoto"
    resume = "ResumeCollado.pdf"
